core/src/main/java/org/apache/any23/extractor/microdata/MicrodataParser.java

Trivial patch which addresses a recent mailing list item
http://www.mail-archive.com/user%40any23.apache.org/msg00166.html

ANY23-131 Nested Microdata are not extracted

---

pom.xml

Trivial upgrade of sesame deps

ANY23-248 NTriplesWriter on hadoop : issue with MIME type/Upgrade sesame dependencies to 2.7.14

---

mime/src/main/java/org/apache/any23/mime/NaiveMIMETypeDetector.java
mime/src/test/java/org/apache/any23/mime/TikaMIMETypeDetectorTest.java
plugins/office-scraper/src/main/java/org/apache/any23/plugin/officescraper/ExcelExtractor.java
pom.xml

Hi Folks,
Please see PR for master branch which addresses ANY23-250

ANY23-250 Upgrade to Tika 1.7

---

mime/src/main/resources/org/apache/any23/mime/mimetypes.xml

Hi @michelemostarda, please check out the results which I now get when I run the following
lmcgibbn@LMC-032857 /usr/local/any23/core/target/appassembler(master) $ ./bin/any23 rover -l output.log -o output.txt -s "http://people.apache.org/~lewismc/example-jsonld.jsonld"
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
------------------------------------------------------------------------
Apache Any23 :: rover
------------------------------------------------------------------------
>Summary:
-total calls: 2
-total triples: 5
-total runtime: 12 ms!
-tripls/ms: 0
-ms/calls: 6
>Extractor: consolidation-extractor
-total calls: 1 …

ANY23-253 JSON-LD cannot be processed by Rover

---

pom.xml

This issue addresses https://issues.apache.org/jira/browse/ANY23-278

ANY23-278 Upgrade all Maven plugin versions in parent pom.xml

---

pom.xml

This issue addresses https://issues.apache.org/jira/browse/ANY23-296

ANY23-296 Tar complains about groupid value being too big

---

cli/src/test/resources/log4j.properties

- Fix ANY23-305 :: Configure appender for log4j
- Fix ANY23-301 :: Stream loggs into STDERR
- add external file at conf/log4.properties
Signed-off-by:Jacek Grzebyta <grzebyta.dev@gmail.com>

ANY23-305 , ANY23-301 Configure appender for logs

---

src/site/xdoc/download.xml.vm

FIX ANY23-309 (spelling error)
FIX ANY23-306 (correct URLs for "WAR package with dependencies")

Downloads page updates

---

src/site/apt/index.apt

Bulleted list is not rendered at http://any23.apache.org/
I think this fixes it

Formatting was off

---

core/src/main/java/org/apache/any23/extractor/yaml/ElementsProcessor.java
core/src/main/java/org/apache/any23/extractor/yaml/YAMLExtractor.java
core/src/main/java/org/apache/any23/rdf/RDFUtils.java
core/src/test/java/org/apache/any23/extractor/yaml/ElementsProcessorTest.java

- replaces Map.Entry by dedicated small getters bean.
- other small changes
Signed-off-by:Jacek Grzebyta <grzebyta.dev@gmail.com>

ANY23-312 Solved issues in javadoc description 

---

api/src/main/java/org/apache/any23/vocab/OGP.java
api/src/main/java/org/apache/any23/vocab/OGPArticle.java
api/src/main/java/org/apache/any23/vocab/OGPBook.java
api/src/main/java/org/apache/any23/vocab/OGPMusic.java
api/src/main/java/org/apache/any23/vocab/OGPProfile.java
api/src/main/java/org/apache/any23/vocab/OGPVideo.java
core/src/test/java/org/apache/any23/extractor/rdfa/AbstractRDFaExtractorTestCase.java
core/src/test/java/org/apache/any23/extractor/rdfa/RDFa11ExtractorTest.java
core/src/test/java/org/apache/any23/vocab/RDFSchemaUtilsTest.java
test-resources/src/test/resources/html/rdfa/opengraph-music-song-object-type.html
test-resources/src/test/resources/html/rdfa/opengraph-structured-properties.html

This PR addresses https://issues.apache.org/jira/browse/ANY23-298

ANY23-298 Revisit the OGP.java vocabulary and update it

---

api/src/main/java/org/apache/any23/writer/WriterFactoryRegistry.java
service/src/main/java/org/apache/any23/servlet/RedirectServlet.java
service/src/main/java/org/apache/any23/servlet/Servlet.java
service/src/main/java/org/apache/any23/servlet/WebResponder.java
service/src/main/java/org/apache/any23/servlet/conneg/ContentTypeNegotiator.java
service/src/main/java/org/apache/any23/servlet/conneg/MediaRangeSpec.java
service/src/main/resources/form.html

This issue primarily addresses https://issues.apache.org/jira/browse/ANY23-314
Additional changes are trivial code cleanups.

ANY23-314 Service fails to return extraction in case of extraction error

---

api/src/main/java/org/apache/any23/extractor/ExtractionParameters.java
cli/src/main/java/org/apache/any23/cli/Rover.java
core/src/main/java/org/apache/any23/extractor/SingleDocumentExtraction.java
core/src/main/java/org/apache/any23/extractor/rdf/BaseRDFExtractor.java
core/src/main/java/org/apache/any23/validator/DefaultValidationReportBuilder.java
core/src/main/java/org/apache/any23/validator/DefaultValidator.java
core/src/main/java/org/apache/any23/validator/ValidationReport.java
core/src/main/java/org/apache/any23/validator/rule/AboutNotURIRule.java
core/src/main/java/org/apache/any23/validator/rule/MetaNameMisuseFix.java
core/src/main/java/org/apache/any23/validator/rule/MetaNameMisuseRule.java
core/src/main/java/org/apache/any23/validator/rule/MissingItemscopeAttributeValueFix.java
core/src/main/java/org/apache/any23/validator/rule/MissingItemscopeAttributeValueRule.java
core/src/main/java/org/apache/any23/validator/rule/MissingOpenGraphNamespaceRule.java
core/src/main/java/org/apache/any23/validator/rule/OpenGraphNamespaceFix.java
core/src/test/java/org/apache/any23/Any23Test.java
core/src/test/java/org/apache/any23/validator/DefaultValidatorTest.java
core/src/test/java/org/apache/any23/validator/XMLValidationReportSerializerTest.java
service/src/main/java/org/apache/any23/servlet/RedirectServlet.java
service/src/main/java/org/apache/any23/servlet/Servlet.java
service/src/main/java/org/apache/any23/servlet/WebResponder.java
test-resources/src/test/resources/microdata/microdata-basic.html

This issue addresses https://issues.apache.org/jira/browse/ANY23-318
It also includes several improvements which will help others when debugging code. Furthermore I've corrected > Java7 code conventions whenever possible.
Apologies that this ended up a larger patch than described in the JIRA issue description however I feel it adequately addresses the issue at hand.

ANY23-318 ExtractionException handling in BaseRDFExtractor.java kills entire extraction

---

core/src/main/java/org/apache/any23/extractor/html/EmbeddedJSONLDExtractor.java
core/src/test/java/org/apache/any23/extractor/html/EmbeddedJSONLDExtractorTest.java
test-resources/src/test/resources/html/html-body-embedded-jsonld-extractor.html
test-resources/src/test/resources/html/html-head-and-body-embedded-jsonld-extractor.html

Pretty self explanatory. Simply changed one xpath expression. Also added relevant tests.
mvn clean install -> all tests pass.

ANY23-291 Allow JSONLD scripts to be located anywhere in document

---

core/src/test/java/org/apache/any23/extractor/rdfa/RDFa11ExtractorTest.java
test-resources/src/test/resources/html/rdfa/rdfa-issue227.html
test-resources/src/test/resources/html/rdfa/rdfa-issue268-and-317.html
test-resources/src/test/resources/html/rdfa/rdfa-issue271-and-317.html
test-resources/src/test/resources/html/rdfa/rdfa-issue273-and-317.html
test-resources/src/test/resources/html/rdfa/rdfa-issue326-and-267.html

Added tests to ensure that all of these issues were fixed by PR #59, and so that we don't regress on a subsequent PR.

ANY23-227,ANY23-268,ANY23-317,ANY23-271,ANY23-273,ANY23-326,ANY23-267

---

core/src/main/java/org/apache/any23/extractor/rdf/BaseRDFExtractor.java
core/src/test/java/org/apache/any23/extractor/rdfa/RDFa11ExtractorTest.java
test-resources/src/test/resources/html/BBC_News_Scotland.html

This should resolve the remaining problems with the Nutch test cases.
mvn clean test --> all tests pass.
@lewismc any comments?

ANY23-340 Removes doctypes to allow extraction of additional rdfa 1.1 triples

---

cli/pom.xml
core/pom.xml
core/src/main/java/org/apache/any23/extractor/html/HTMLDocument.java
core/src/main/java/org/apache/any23/http/DefaultHTTPClient.java
core/src/main/java/org/apache/any23/http/HTTPClient.java
core/src/main/java/org/apache/any23/source/HTTPDocumentSource.java
core/src/main/java/org/apache/any23/util/LogUtils.java
pom.xml
service/src/main/java/org/apache/any23/servlet/Servlet.java

This is my first stab at removing the decade-out-of-date `commons-httpclient` dependency.
All tests are passing, but I want another set of eyes on this.
@lewismc any comments?

ANY23-341 Remove dependency on defunct commons-httpclient

---

core/src/main/java/org/apache/any23/extractor/microdata/MicrodataExtractor.java
test-resources/src/test/resources/microdata/microdata-nested-expected.nquads
test-resources/src/test/resources/microdata/microdata-richsnippet-expected.nquads
test-resources/src/test/resources/microdata/schemaorg-example-1-expected.nquads
test-resources/src/test/resources/microdata/schemaorg-example-2-expected.nquads

This *pretty major* issue has been open for **seven years**... lol...
mvn clean test -> all tests pass (after rewriting the tests to stop testing for the wrong behavior).

ANY23-16 fix microdata property URIs

---

core/src/main/java/org/apache/any23/extractor/rdf/JSONLDExtractor.java
core/src/test/java/org/apache/any23/extractor/rdf/JSONLDExtractorTest.java
pom.xml

ANY23-343 upgrade to jsonld-java version 0.12.0

---

core/src/main/java/org/apache/any23/extractor/microdata/MicrodataExtractor.java
core/src/test/java/org/apache/any23/extractor/html/AbstractExtractorTestCase.java
core/src/test/java/org/apache/any23/extractor/microdata/MicrodataExtractorTest.java
pom.xml
test-resources/src/test/resources/microdata/microdata-nested-url-resolving-expected.nquads
test-resources/src/test/resources/microdata/microdata-nested-url-resolving.html
test-resources/src/test/resources/microdata/schemaorg-example-2-expected.nquads

ANY23-169 Fixed url resolving errors in MicrodataExtractor

---

core/src/test/java/org/apache/any23/extractor/rdfa/RDFa11ExtractorTest.java
core/src/test/java/org/apache/any23/extractor/rdfa/RDFaExtractorTest.java
test-resources/src/test/resources/html/rdfa/0087.xhtml

Added a test case to ensure we don't inadvertently switch back to buggy behavior.

ANY23-237 added test case to ensure no regression

---

core/src/main/java/org/apache/any23/extractor/ExtractionResultImpl.java

ANY23-337 fixed: BenchmarkTripleHandler reported inaccurate runtimes

---

core/src/main/java/org/apache/any23/extractor/SingleDocumentExtraction.java

ANY23-334 fixed: default language was a UUID

---

service/pom.xml
service/src/main/assembly/README.txt
service/src/main/assembly/server-embedded.xml
service/src/main/bin/any23server
service/src/main/bin/any23server.bat

This issue addresses https://issues.apache.org/jira/browse/ANY23-322
@HansBrende

ANY23-322 Any23 embedded service is broken

---

cli/pom.xml
core/pom.xml
core/src/test/java/org/apache/any23/writer/JSONWriterTest.java
pom.xml
service/src/test/java/org/apache/any23/servlet/ServletTest.java

@lewismc @JulioCCBUcuenca rdf4j version 2.3.2 defaults to pretty printing in the JSONLDWriter, so this PR seems to complement ANY23-231 nicely. Does that work for you?

ANY23-352 updated to rdf4j version 2.3.2

---

core/src/main/java/org/apache/any23/extractor/rdf/BaseRDFExtractor.java

The RDFParseException was caused by the following malformed markup:
`<link rel=\"shortcut icon\">`
Jsoup then cleaned this up into:
`<link rel="\&quot;shortcut" icon\"="">`
The problem with that was that the underlying SAX parser doesn't play well with attribute names that contain quotes, so the attribute name `icon\"` caused the following exception:
```
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 4536; Attribute name "icon" 
associated with an element type "link" must be followed by the ' = ' character.
at org.semarglproject.rdf4j.rdf.rdfa.RDF4JRDFaParser.parse(RDF4JRDFaParser.java:111)
at org.semarglproject.rdf4j.rdf.rdfa.RDF4JRDFaParser.parse(RDF4JRDFaParser.java:95)
at org.apache.any23.extractor.rdf.BaseRDFExtractor.run(BaseRDFExtractor.java:158)
```
My solution to …

ANY23-350 fixed RDFParseException caused by malformed attributes

---

core/src/test/java/org/apache/any23/extractor/html/HCalendarExtractorTest.java
core/src/test/java/org/apache/any23/extractor/rdfa/RDFa11ParserTest.java
encoding/src/test/java/org/apache/any23/encoding/TikaEncodingDetectorTest.java

ANY23-358 fixed junit.framework.Assert & RDFa11Parser deprecation warnings

---

core/src/test/java/org/apache/any23/validator/DefaultValidatorTest.java

Also refactored a bit for code style.

ANY23-360 Resolved Xerces deprecation warnings

---

mime/src/main/java/org/apache/any23/mime/TikaMIMETypeDetector.java

1. resolved tika deprecation warning
2. refactored for code style
3. avoid NullPointerException in `guessMIMEType()`
4. avoid `SecurityException` in `getResourceAsStream()`
5. use synchronization in constructor when initializing static variables
@lewismc any comments?

ANY23-361 resolved tika deprecation warning

---

pom.xml

ANY23-363 updated httpclient/httpcore to 4.5.6/4.4.10

---

plugins/office-scraper/src/main/java/org/apache/any23/plugin/officescraper/ExcelExtractor.java
plugins/office-scraper/src/main/java/org/apache/any23/vocab/Excel.java

ANY23-364 resolved POI deprecation warnings

---

core/src/main/java/org/apache/any23/extractor/microdata/MicrodataParser.java
core/src/test/java/org/apache/any23/extractor/microdata/MicrodataExtractorTest.java
test-resources/src/test/resources/microdata/microdata-bad-properties-expected.nquads
test-resources/src/test/resources/microdata/microdata-bad-properties.html

ANY23-376 fix IllegalArgumentException in microdata extractor

---

core/src/main/java/org/apache/any23/extractor/microdata/ItemPropValue.java
test-resources/src/test/resources/microdata/microdata-bad-properties-expected.nquads

ANY23-377 don't replace empty strings with 'Null'

---

core/src/main/java/org/apache/any23/extractor/rdf/BaseRDFExtractor.java
core/src/test/java/org/apache/any23/extractor/html/EmbeddedJSONLDExtractorTest.java
test-resources/src/test/resources/html/html-jsonld-commas.html

Remove trailing commas from objects and arrays. Also replace semicolons with commas (compare to gson's `JsonReader.setLenient()`). 

ANY23-378 clean commas in JSON-LD

---

pom.xml
src/site/xdoc/download.xml.vm

@lewismc anything else I need to do here to ensure this refactor works properly?

ANY23-367 update 'latest.stable.released' property

---

core/src/main/java/org/apache/any23/extractor/rdf/BaseRDFExtractor.java
core/src/test/java/org/apache/any23/extractor/rdfa/RDFa11ExtractorTest.java
test-resources/src/test/resources/html/rdfa/invalid-xml-character.html

ANY23-379 remove invalid XML characters from document

---

core/src/main/java/org/apache/any23/extractor/rdf/BaseRDFExtractor.java
core/src/test/java/org/apache/any23/extractor/html/EmbeddedJSONLDExtractorTest.java
test-resources/src/test/resources/html/html-jsonld-unescaped-characters.html

ANY23-381 escape illegal characters in JSON-LD strings

---

core/src/main/java/org/apache/any23/extractor/rdf/BaseRDFExtractor.java
core/src/main/java/org/apache/any23/extractor/rdf/JSONLDExtractor.java
core/src/main/java/org/apache/any23/extractor/rdf/RDFParserFactory.java
core/src/test/java/org/apache/any23/extractor/html/EmbeddedJSONLDExtractorTest.java
test-resources/src/test/resources/html/html-jsonld-fatal-error.html

ANY23-382 don't kill extraction on fatal json parsing errors

---

cli/pom.xml
core/pom.xml
core/src/main/java/org/apache/any23/extractor/rdf/BaseRDFExtractor.java
core/src/test/java/org/apache/any23/extractor/html/EmbeddedJSONLDExtractorTest.java
core/src/test/java/org/apache/any23/extractor/rdf/JSONLDExtractorTest.java
encoding/pom.xml
mime/pom.xml
pom.xml
test-resources/src/test/resources/html/html-jsonld-bad-character.html

ANY23-383 allow all unicode space chars in JSON-LD

---

core/src/main/java/org/apache/any23/extractor/microdata/MicrodataExtractor.java
core/src/test/java/org/apache/any23/extractor/microdata/MicrodataExtractorTest.java
test-resources/src/test/resources/microdata/example2.html
test-resources/src/test/resources/microdata/example5.html

This PR should ensure that our microdata extractor is compliant with the standard default microdata registry in terms of vocabulary expansion and property URI generation.

ANY23-404 hardcode default microdata registry

---

core/src/main/java/org/apache/any23/extractor/microdata/ItemPropValue.java
core/src/main/java/org/apache/any23/extractor/microdata/MicrodataExtractor.java
core/src/main/java/org/apache/any23/extractor/microdata/MicrodataParser.java
core/src/main/java/org/apache/any23/rdf/RDFUtils.java
test-resources/src/test/resources/microdata/microdata-nested-url-resolving-expected.nquads

See http://w3c.github.io/microdata-rdf/#dfn-property-values

ANY23-405 Parse microdata property values correctly

---

core/src/main/java/org/apache/any23/extractor/microdata/ItemScope.java
core/src/main/java/org/apache/any23/extractor/microdata/MicrodataExtractor.java
core/src/main/java/org/apache/any23/extractor/microdata/MicrodataParser.java

This PR addresses the failed `Test 0056: token property and multiple @itemtypes from different vocabularies` microdata test.

ANY23-409 allow multiple microdata itemtype values

---

cli/pom.xml

This PR fixes the issue in question. However I am unaware of whether this will have any unwanted side-effects.

ANY23-422 Error message when any23 cli tool used

---

core/src/test/java/org/apache/any23/extractor/rdf/FunctionalSyntaxExtractorTest.java
pom.xml
service/pom.xml

This PR will net us a bunch of additional bugfixes in various dependencies before we release 2.3.

ANY23-424 Update dependencies

---

cli/src/test/java/org/apache/any23/cli/ExtractorsFlowTest.java
cli/src/test/java/org/apache/any23/cli/SimpleRoverTest.java
cli/src/test/java/org/apache/any23/cli/ToolTestBase.java
cli/src/test/java/org/apache/any23/cli/YAMLRoverTest.java
core/src/test/java/org/apache/any23/AbstractAny23TestBase.java
core/src/test/java/org/apache/any23/Any23Test.java
core/src/test/java/org/apache/any23/extractor/SingleDocumentExtractionTest.java
core/src/test/java/org/apache/any23/extractor/csv/CSVReaderBuilderTest.java
core/src/test/java/org/apache/any23/extractor/html/AbstractExtractorTestCase.java
core/src/test/java/org/apache/any23/extractor/html/EncodingTest.java
core/src/test/java/org/apache/any23/extractor/html/HCardExtractorTest.java
core/src/test/java/org/apache/any23/extractor/html/HReviewExtractorTest.java
core/src/test/java/org/apache/any23/extractor/html/SpeciesExtractorTest.java
core/src/test/java/org/apache/any23/extractor/html/TagSoupParserTest.java
core/src/test/java/org/apache/any23/extractor/html/TitleExtractorTest.java
core/src/test/java/org/apache/any23/extractor/html/TurtleHTMLExtractorTest.java
core/src/test/java/org/apache/any23/extractor/microdata/MicrodataExtractorTest.java
core/src/test/java/org/apache/any23/extractor/microdata/MicrodataParserTest.java
core/src/test/java/org/apache/any23/extractor/rdf/TurtleExtractorTest.java
core/src/test/java/org/apache/any23/extractor/rdfa/AbstractRDFaExtractorTestCase.java
core/src/test/java/org/apache/any23/extractor/rdfa/RDFa11ExtractorTest.java
core/src/test/java/org/apache/any23/extractor/rdfa/RDFaExtractorTest.java
core/src/test/java/org/apache/any23/extractor/yaml/YAMLExtractorTest.java
core/src/test/java/org/apache/any23/extractor/yaml/YAMLTikaParserTest.java
core/src/test/java/org/apache/any23/util/DiscoveryUtilsTest.java
mime/src/test/java/org/apache/any23/mime/TikaMIMETypeDetectorTest.java
plugins/basic-crawler/src/test/java/org/apache/any23/plugin/crawler/SiteCrawlerTest.java
pom.xml
service/src/test/java/org/apache/any23/servlet/ServletTest.java

This issue addresses https://issues.apache.org/jira/browse/ANY23-429 and enabled me to build the new Website and publish to SVN

ANY23-429 Website Build Fails due to Javadoc issues

---

cli/src/main/assembly/bin.xml
core/src/test/java/org/apache/any23/extractor/html/AbstractExtractorTestCase.java
plugins/basic-crawler/src/main/assembly/bin.xml
plugins/html-scraper/src/main/assembly/bin.xml
plugins/office-scraper/src/main/assembly/bin.xml
pom.xml
service/pom.xml
service/src/main/assembly/server-embedded.xml

This PR addresses https://issues.apache.org/jira/browse/ANY23-444
In it's current state the PR introduces at least one test failure as follows
```
[ERROR] Failures:
[ERROR]   EmbeddedJSONLDExtractorTest.testJSONLDUnescapedCharacters:76->AbstractExtractorTestCase.assertExtract:227->AbstractExtractorTestCase.assertExtract:212->AbstractExtractorTestCase.assertNoIssues:386 Unexpected issue for extractor html-embedded-jsonld : [FATAL: 	'Unrecognized character escape (CTRL-CHAR, code 8)' 	(5,31), FATAL: 	'Illegal unquoted character ((CTRL-CHAR, code 10)): has to be escaped using backslash to be included in string value' 	(6,43), FATAL: 	'Illegal unquoted character ((CTRL-CHAR, code 10)): has to be escaped using backslash to be included in string value' 	(6,22)]
[INFO]
[ERROR] Tests run: 449, …
```

ANY23-444 Update all dependencies and plugins

---

core/src/main/java/org/apache/any23/validator/DefaultValidator.java
core/src/main/java/org/apache/any23/validator/Rule.java
core/src/main/java/org/apache/any23/validator/Validator.java
pom.xml

This issue addresses https://issues.apache.org/jira/browse/ANY23-183
You can also see I bumped the javac version to 13... which is what I am using across the board now. If this is not desired then i can roll this back.

ANY23-183 Address javac warning's in Any23 code base

---

core/src/main/java/org/apache/any23/extractor/rdf/BaseRDFExtractor.java
core/src/main/java/org/apache/any23/extractor/rdf/JSONLDExtractor.java
core/src/main/java/org/apache/any23/extractor/rdf/JSONLDJavaSink.java
pom.xml

Upgrade rdf4j to v3.0.0 and remove jsonld hack. I also took out the rdf4j middleman when working with the jsonld-java library, which will allow us to more easily tinker with jsonld-java in the future instead of resorting to terrible hacks.

ANY23-433 upgrade rdf4j to v3.0.0

---

cli/pom.xml
core/pom.xml
core/src/main/java/org/apache/any23/extractor/calendar/BaseCalendarExtractor.java
core/src/main/java/org/apache/any23/extractor/html/HCardExtractor.java
core/src/main/java/org/apache/any23/extractor/microdata/ItemScope.java
core/src/main/java/org/apache/any23/extractor/microdata/MicrodataParser.java
core/src/main/java/org/apache/any23/rdf/Any23ValueFactoryWrapper.java
core/src/main/java/org/apache/any23/util/StringUtils.java
pom.xml

Easier than I thought it would be.

ANY23-439 replace commons-lang with commons-lang3

---

api/src/main/java/org/apache/any23/configuration/Setting.java
api/src/main/java/org/apache/any23/configuration/Settings.java
api/src/main/java/org/apache/any23/writer/WriterFactory.java
core/src/main/java/org/apache/any23/extractor/yaml/ElementsProcessor.java
core/src/main/java/org/apache/any23/http/HTTPClient.java
core/src/main/java/org/apache/any23/rdf/RDFUtils.java
core/src/main/java/org/apache/any23/util/StreamUtils.java
csvutils/src/main/java/org/apache/any23/extractor/csv/CSVReaderBuilder.java
plugins/basic-crawler/src/main/java/org/apache/any23/plugin/crawler/SiteCrawler.java
plugins/office-scraper/src/main/java/org/apache/any23/vocab/Excel.java
pom.xml
service/src/main/java/org/apache/any23/servlet/conneg/ContentTypeNegotiator.java
service/src/main/java/org/apache/any23/servlet/conneg/MediaRangeSpec.java
src/site/apt/configuration.apt

This PR addresses https://issues.apache.org/jira/browse/ANY23-426

ANY23-426 Address Javadoc WARNING's 

---

pom.xml

This PR addresses https://issues.apache.org/jira/browse/ANY23-436
Trivial.

ANY23-436 Upgrade commons-csv to v1.7

---

pom.xml

This issue addresses https://issues.apache.org/jira/browse/ANY23-437
Trivial.

ANY23-437 Upgrade snakeyaml to v1.25

---

pom.xml

This is a simple batch dep and plugin update... verified that it does not break any unit tests with mvn clean install

ANY23-450 Update Maven deps and plugin versions

---

.github/pull_request_template.md
.github/workflows/master-build.yml

PR addresses https://issues.apache.org/jira/browse/ANY23-456

[ANY23-456] Add Github Action against Any23 pull requests

---

.asf.yaml

This PR addresses https://issues.apache.org/jira/browse/ANY23-459

ANY23-459 Create git - .asf.yaml for ANY23

---

.asf.yaml

Trivial update to invalid label

Correct invalid label

---

.github/workflows/master-build.yml
core/src/main/java/org/apache/any23/extractor/rdf/JSONLDExtractor.java
core/src/test/java/org/apache/any23/Any23Test.java
pom.xml

This issue relates to https://issues.apache.org/jira/browse/ANY23-461
I think there may be a failing test but I can wait for the CI to point that out.

[ANY23-461] Upgrade Any23 to JDK11

---

.github/dependabot.yml

This PR addresses https://issues.apache.org/jira/browse/ANY23-485

ANY23-485 Activate dependabot on Any23 codebase

---

pom.xml

This PR supersedes https://github.com/apache/any23/pull/193 and addresses https://issues.apache.org/jira/browse/ANY23-503

ANY23-503 Bump apache from 21 to 24

---

.github/workflows/master-build.yml
README.md
pom.xml

This PR addresses https://issues.apache.org/jira/browse/ANY23-546
I need to wait for root@ to create the `SONAR_TOKEN` before this can be merged otherwise the build will fail.

ANY23-546 Implement sonarcloud.io in Any23 continuous integration

---

pom.xml

This is a test PR to test that snarcloud.io analysis can be executed from an internal branch (rather than a branch from a forked repository).

Test PR to make trivial update to pom.xml and test sonarcloud.io PR analysis

---

pom.xml

Addresses https://issues.apache.org/jira/browse/ANY23-572

ANY23-572 Upgrade owlapi to 5.1.20

---

.github/workflows/master-build.yml
jacoco-report-aggregate/pom.xml
pom.xml

Issue addresses https://issues.apache.org/jira/browse/ANY23-588

ANY23-588 Add code coverage metrics to Sonarcloud.io analysis
