apache/any23

- core/src/main/java/org/apache/any23/extractor/html/DomUtils.java
- core/src/main/java/org/apache/any23/extractor/html/EmbeddedJSONLDExtractor.java
- core/src/main/java/org/apache/any23/extractor/html/EmbeddedJSONLDExtractorFactory.java
- core/src/main/java/org/apache/any23/extractor/rdf/BaseRDFExtractor.java
- core/src/main/resources/org/apache/any23/extractor/html/example-embedded-jsonld.html
- core/src/main/resources/org/apache/any23/prefixes/prefixes.properties
- core/src/test/java/org/apache/any23/extractor/html/EmbeddedJSONLDExtractorTest.java
- plugins/integration-test/src/test/java/org/apache/any23/plugin/PluginIT.java
- test-resources/src/test/resources/html/html-embedded-jsonld-extractor.html
Initial patch for this support. 
It is not working correctly @ansell can you have a look into the parsing of JSONLD textual content?
I've provided a '//' comment to where I can see the correct parser being selected. It seems to not parse and extract the JSONLD so I know I am doing something wrong.
Thank you very much @ansell if you can have a wee look.
> ANY23-226 Extract JSON-LD embedded in HTML

- core/src/main/java/org/apache/any23/extractor/html/microformats2/annotations/package-info.java
- core/src/main/java/org/apache/any23/extractor/microdata/ItemPropValue.java
- core/src/test/java/org/apache/any23/extractor/microdata/MicrodataParserTest.java
When multiple HTML documents are parsed concurrently in different threads, the MicrodataParser will sometimes throw very weird Exceptions or deliver broken values of date properties. I tracked it to a static SimpleDateFormat field in ItemPropValue. SimpleDateFormat is not thread-safe and should never be used like this. 
I wrote a unit test that tries to parse the same document in 10 concurrent threads about 100 times each. Then it gets a value of the "birthday" property. In all thousand cases the value should be the same. On my machine this test fails each time with various errors. With the fix - the test passes each time. 
The test uses a cyclic barrier and ensures that only in-memory data is used, so that I/O overhead and thread creation overhead do not interfere with the actual …
> Fix for a ThreadSafety issue in ItemPropValue

- .gitignore
- api/pom.xml
- core/src/main/assembly/bin.xml
- csvutils/pom.xml
- encoding/pom.xml
- mime/pom.xml
- nquads/pom.xml
- test-resources/pom.xml
This issue addresses https://issues.apache.org/jira/browse/ANY23-277
It also adds some configuration to .gitignore for the any23-site as well as Eclipse files.
Would like to commit EoB today if possible.
> ANY23-277 Any23 master branch will not build to to build due to lacking maven-assembly-plugin

- core/src/main/java/org/apache/any23/extractor/SingleDocumentExtraction.java
- core/src/main/java/org/apache/any23/extractor/rdf/BaseRDFExtractor.java
- core/src/main/java/org/apache/any23/validator/DefaultValidator.java
- core/src/main/java/org/apache/any23/validator/rule/MetaNameMisuseRule.java
- core/src/main/java/org/apache/any23/validator/rule/MissingItemscopeAttributeValueFix.java
- core/src/main/java/org/apache/any23/validator/rule/MissingItemscopeAttributeValueRule.java
- core/src/main/java/org/apache/any23/validator/rule/MissingOpenGraphNamespaceRule.java
- core/src/main/java/org/apache/any23/validator/rule/OpenGraphNamespaceFix.java
- core/src/test/java/org/apache/any23/Any23Test.java
- core/src/test/java/org/apache/any23/validator/DefaultValidatorTest.java
- core/src/test/resources/log4j.properties
- src/site/apt/index.apt
- test-resources/src/test/resources/org/apache/any23/validator/microdata-basic.html
Hi Folks,
PR which fixes this issue locally. I am getting clean builds now again after introducing this new MissingItemscopeAttributeValueRule class.
> ANY23-247 FIX Attribute name itemscope associated with an element type html must be followed by the ' = ' character.

- core/pom.xml
- core/src/main/assembly/bin.xml
- core/src/test/resources/log4j.properties
- csvutils/src/test/resources/log4j.properties
- mime/src/test/resources/log4j.properties
- plugins/office-scraper/src/test/resources/log4j.properties
- service/src/test/resources/log4j.properties
This PR addresses a few things
* Packages log4j configuration with core appassembler
* adds 4 missing license headers
* changes core log4j verbosity from DEBUG to INFO
> ANY23-293 Package log4j configuration with core appassembler

- src/site/apt/index.apt
- src/site/apt/supported-formats.apt
Documentation updates:
1. supported-formats.apt page: now has working links to N-QUADS documentation; and better information about when current N-QUADS spec will be supported.
2. site/index.apt file was missing a set of matching "{","}" in two places.
> ANY23-235 NQuads links broken on Supported Formats Page

- .gitignore
Fix ANY23-300
- Add `**/nb*.xml` pattern into .gitignore to ignore NetBeans configuration files
Signed-off-by: Jacek Grzebyta <grzebyta.dev@gmail.com>
> ANY23-300: Ignore NetBeans configuration files

- README.md
Before this commit, the doc was pointing to the `core` project, which does not contain the Any23 command line interface
> Update CLI proper documentation

- core/pom.xml
- core/src/main/java/org/apache/any23/extractor/rdf/FunctionalSyntaxExtractor.java
- core/src/main/java/org/apache/any23/extractor/rdf/FunctionalSyntaxExtractorFactory.java
- core/src/main/java/org/apache/any23/extractor/rdf/ManchesterSyntaxExtractor.java
- core/src/main/java/org/apache/any23/extractor/rdf/ManchesterSyntaxExtractorFactory.java
- core/src/main/java/org/apache/any23/extractor/rdf/RDFParserFactory.java
- core/src/main/resources/META-INF/services/org.apache.any23.extractor.ExtractorFactory
- core/src/main/resources/org/apache/any23/extractor/rdf/example-functionalsyntax.ofn
- core/src/main/resources/org/apache/any23/extractor/rdf/example-manchestersyntax.omn
- core/src/test/java/org/apache/any23/extractor/rdf/FunctionalSyntaxExtractorTest.java
- core/src/test/java/org/apache/any23/extractor/rdf/ManchesterSyntaxExtractorTest.java
- plugins/integration-test/src/test/java/org/apache/any23/plugin/PluginIT.java
- pom.xml
- test-resources/src/test/resources/text/owl-functional/example-functionalsyntax.ofn
- test-resources/src/test/resources/text/owl-manchester/example-manchestersyntax.omn
Adds OWL parsing support through OWLAPI via RDF4J Rio for Manchester Syntax and Functional Syntax.
Signed-off-by: Peter Ansell <p_ansell@yahoo.com>
> ANY23-257 : Add OWL parser support to Any23 via OWLAPI and RDF4J

- core/src/main/java/org/apache/any23/extractor/microdata/MicrodataParser.java
<sometag content="something" /> should be considered, regardless if `content` is not a valid
attribute of `sometag`.
The specification for microdata[1] details that an elements content attribute should be considered
before text content.
Any23 doesn't currently do this, it only considers `content` for `meta` tags which is the only
HTML tag which is suppose to have a `content` but not all sites follow HTML specifications.
Updating the microdata parser to be able to get `content` from any element should it exist.
[1] https://www.w3.org/TR/microdata/#values
Signed-off-by: Ian Duffy <ian.duffy@zalando.ie>
> Support attribute content on all fields.

- cli/src/test/java/org/apache/any23/cli/MicrodataParserTest.java
- core/src/test/java/org/apache/any23/Any23Test.java
- plugins/basic-crawler/src/test/java/org/apache/any23/cli/CrawlerTest.java
This issue re-enables the 'online' tests as essentially the jsonld tests require fetching of Web content anyways.
> ANY23-140 - Revise Any23 tests to remove fetching of web content

- pom.xml
The any23-repository-external repository will currently cause setups forbidding fetching packages over plain HTTP to error. Notably this includes Leiningen. Luckily we can just use the HTTPS url instead.
> Fix HTTP repository link: change to HTTPS

- api/src/main/resources/default-configuration.properties
- core/pom.xml
- core/src/main/java/org/apache/any23/extractor/html/EmbeddedJSONLDExtractor.java
- core/src/main/java/org/apache/any23/extractor/html/HCardExtractor.java
- core/src/main/java/org/apache/any23/extractor/html/HTMLMetaExtractor.java
- core/src/main/java/org/apache/any23/extractor/html/TagSoupParser.java
- core/src/main/java/org/apache/any23/extractor/html/TagSoupParsingConfiguration.java
- core/src/test/java/org/apache/any23/extractor/microdata/MicrodataParserTest.java
- pom.xml
This should also indirectly fix ANY23-317, ANY23-273, ANY23-267, and ANY23-326.
I also added a "any23.tagsoup.legacy" flag in default-configuration.properties to allow switching back to the NekoHTML version.
I ran the full suite of tests against this fork using "mvn clean install", and all tests are passing.
Please let me know if there's anything more I can do to improve this pull request!
> ANY23-324 Changed default html parser from NekoHTML to Jsoup. 

- core/src/main/java/org/apache/any23/rdf/RDFUtils.java
No need to see a stack trace every time `isAbsoluteIRI` returns `false`.
> ANY23-327 Change log level to debug for RDFUtils.isAbsoluteIRI()

- core/src/main/java/org/apache/any23/extractor/csv/CSVExtractor.java
- csvutils/src/main/java/org/apache/any23/extractor/csv/CSVReaderBuilder.java
- pom.xml
I upgraded the commons-csv dependency from `1.0-SNAPSHOT-rev1148315` to `1.5`.
On running `mvn clean install`, all tests pass.
A couple of minor code changes I made along the way:
1. Deleted dead code in `if (delimiter.length() != 1 || delimiter.equals(""))`
2. Added a null-check in `CSVExtractor.processHeader()`
3. Deleted `NULL_CHAR = ' '` from `CSVReaderBuilder`. Not sure why that was being used as a comment marker--guessing it was meant to disable comments during strategy testing, which the default `CSVFormat` does already.
4. Deleted non-standard use of the character `'` for encapsulation. Not sure why that was being used as such. Both `CSVFormat.DEFAULT` and the defunct `CSVStrategy.DEFAULT_STRATEGY`, as well as the RFC 4180 standard use `"` as the encapsulation character.
> ANY23-264 Upgrade to use public commons-csv instead of custom SNAPSHOT

- core/src/main/java/org/apache/any23/extractor/html/EmbeddedJSONLDExtractor.java
- core/src/main/java/org/apache/any23/extractor/rdf/BaseRDFExtractor.java
- core/src/test/java/org/apache/any23/extractor/html/EmbeddedJSONLDExtractorTest.java
- test-resources/src/test/resources/html/html-jsonld-strip-comments.html
I stripped single-line and multi-line comments from json-ld content, as well as CDATA markers.
Also added a test case.
`mvn clean install` -> All tests pass.
> ANY23-328 Strip comments from json-ld to make parsing more lenient

- core/src/main/java/org/apache/any23/extractor/rdf/BaseRDFExtractor.java
- core/src/test/java/org/apache/any23/extractor/html/EmbeddedJSONLDExtractorTest.java
- test-resources/src/test/resources/html/html-jsonld-strip-comments.html
This is my bad for not catching this when I first implemented json comment stripping, but resolved now. Sorry folks!
> ANY23-338 fixed problem with json comment stripping

- core/src/main/java/org/apache/any23/extractor/microdata/MicrodataExtractor.java
- core/src/test/java/org/apache/any23/extractor/microdata/MicrodataExtractorTest.java
I fixed the itemscope hashcode collision problem documented in ANY23-339, as well as loosening the restriction on subject resources to allow absolute URIs as subjects. 
mvn clean test --> all tests pass
@lewismc Any comments before I merge this?
> ANY23-339 fixes itemscope hashcode collision problem, allows absolute URIs as subjects

- core/src/main/java/org/apache/any23/extractor/rdf/JSONLDExtractor.java
- core/src/test/java/org/apache/any23/extractor/rdf/JSONLDExtractorTest.java
This is a hacky patch for Any23 that does exactly the same thing my [JSONLD-JAVA pull request](https://github.com/jsonld-java/jsonld-java/pull/228) does.
With this patch in place, the amortized extraction time for the site https://www.guthriegreen.com dropped from 30 seconds to 0.3 seconds, a difference of **two orders of magnitude**!!! 😱😮😵
This patch should be removed as soon as we can upgrade to JSONLD-JAVA version 0.11.2.
mvn clean test -> all tests pass.
@lewismc @ansell Any comments before I merge this?
> ANY23-336 Hacky patch to tide us over until jsonldjava 0.11.2 release

- core/src/main/java/org/apache/any23/extractor/rdf/BaseRDFExtractor.java
- pom.xml
I also had to add `BasicParserSettings.VERIFY_RELATIVE_URIS` as a non-fatal error, due to differences in the ways that version 2.2.4 and 2.3.0 calculated whether a URI is *opaque*:
2.2.4 called any URI with a null path opaque (which could never happen)
2.3.0 called a URI opaque if it had a non-null scheme and its path did not begin with "/"
Without classifying the above error as non-fatal, errors occurred in the turtle parser test. Since the document IRI did not end with "/", it was classified as "opaque" by version 2.3.0, hence attempting to resolve a relative IRI against it resulted in an error.
> ANY23-323 Update Eclipse RDF4J version to 2.3.0

- core/src/main/java/org/apache/any23/extractor/microdata/ItemScope.java
- core/src/main/java/org/apache/any23/extractor/microdata/MicrodataParser.java
- core/src/test/java/org/apache/any23/extractor/microdata/MicrodataExtractorTest.java
- test-resources/src/test/resources/microdata/microdata-bad-types-expected.nquads
- test-resources/src/test/resources/microdata/microdata-bad-types.html
- test-resources/src/test/resources/microdata/tel-test.html
I did two things: 
(1) Treat blank microdata types as if they were null
(2) For other varieties of malformed microdata types, first attempt to fix them by trimming leading & trailing whitespaces and url-encoding illegal characters. If that fails, then only throw a fatal error if the microdata parser error mode is set to STOP_AT_FIRST_ERROR; otherwise, add the error to the error list, treat the type as if it were null, and continue parsing.
@lewismc what do you think?
> ANY23-348 handle malformed microdata types gracefully

- core/src/main/java/org/apache/any23/extractor/html/HCardExtractor.java
- core/src/main/java/org/apache/any23/extractor/html/HTMLDocument.java
- core/src/test/java/org/apache/any23/extractor/html/HCardExtractorTest.java
- test-resources/src/test/resources/microformats/hcard/null-pointer.html
This PR:
1. fixes the NullPointerExceptions that have occurred in HCardExtractor
2. supports the 'srcset' attribute in obtaining urls from img elements
3. fixes the fallback url extraction method to align with the spec by only obtaining url text from 'value'-class elements, or, if none defined, from non-'type'-class elements.
> ANY23-351 fixed NullPointerException in HCardExtractor

- core/src/main/java/org/apache/any23/rdf/Any23ValueFactoryWrapper.java
- core/src/test/java/org/apache/any23/Any23Test.java
For string literals of datatype "langString" with no language tag, I'm simply falling back to type "string" (or using the default language if specified).
@lewismc any comments?
> ANY23-353 fallback on string datatype for langstring with no lang

- core/src/main/java/org/apache/any23/extractor/rdfa/RDFa11Parser.java
- core/src/main/java/org/apache/any23/extractor/rdfa/RDFa11ParserException.java
The [RDFParserFactory](https://github.com/apache/any23/blob/master/core/src/main/java/org/apache/any23/extractor/rdf/RDFParserFactory.java) uses Rio implementations, and as a consequence of this, the [RDFa11Parser](https://github.com/apache/any23/blob/master/core/src/main/java/org/apache/any23/extractor/rdfa/RDFa11Parser.java) is not longer used. Thus, it needs to be deprecated.
> ANY23-355: Deprecate RDFa11Parser since Rio implementations are used instead

- plugins/html-scraper/src/test/java/org/apache/any23/plugin/htmlscraper/HTMLScraperExtractorTest.java
- plugins/office-scraper/src/test/java/org/apache/any23/plugin/officescraper/ExcelExtractorTest.java
1. Changed `anyObject()` method to its alias `any()`
2. Removed usages of `Matchers` class
> resolved mockito deprecation warnings

- core/src/test/java/org/apache/any23/Any23Test.java
`org.apache.commons.io.IOUtils.toString(InputStream)` became deprecated in version 2.5. 
> ANY23-359 resolved deprecation warning in Any23Test

- api/src/main/java/org/apache/any23/plugin/Author.java
- cli/src/main/java/org/apache/any23/cli/PluginVerifier.java
- service/src/main/java/org/apache/any23/servlet/WebResponder.java
Resolved the following warnings:
- Annotation `Author.class` is not retained for reflective access (in `o.a.a.cli.PluginVerifier`)
- `o.a.a.cli.PluginVerifier` uses unchecked or unsafe operations
- `sun.security.validator.ValidatorException` is internal proprietary API and may be removed in a future release (in `o.a.a.servlet.WebResponder`)
> ANY23-365 resolved additional warnings

- core/src/main/java/org/apache/any23/extractor/rdf/BaseRDFExtractor.java
- core/src/main/java/org/apache/any23/extractor/rdf/RDFParserFactory.java
- core/src/main/java/org/apache/any23/extractor/rdf/RDFXMLExtractor.java
- core/src/main/java/org/apache/any23/extractor/rdf/TriXExtractor.java
- core/src/main/java/org/apache/any23/rdf/RDFUtils.java
- mime/src/main/java/org/apache/any23/mime/TikaMIMETypeDetector.java
1. resolved rdf4j deprecation warnings
2. refactored for code style and improved singleton pattern in `RDFParserFactory`
3. updated no-arg constructors in `RDFXMLExtractor` and `TriXExtractor` to match their javadoc specs, along with the behavior all the other RDF extractor classes' no-arg constructors
@lewismc any comments before I merge this in?
> ANY23-362 resolved rdf4j deprecation warnings

- cli/pom.xml
- core/pom.xml
- encoding/pom.xml
- mime/pom.xml
1. Excluded `commons-logging` from dependencies to ensure `jcl-over-slf4j` works as expected
2. Changed deprecated 'name' tag to 'id' in `appassembler-maven-plugin`
> ANY23-366 resolved additional build warnings

- core/src/main/java/org/apache/any23/extractor/microdata/ItemScope.java
- core/src/test/java/org/apache/any23/extractor/microdata/MicrodataExtractorTest.java
- test-resources/src/test/resources/microdata/microdata-missing-scheme.html
Fixes microdata itemtype urls that are lacking a scheme by using a default scheme of "http".
mvn clean test -> all tests passed.
> ANY23-374 fix schemeless microdata urls

- cli/src/main/java/org/apache/any23/cli/BaseTool.java
- cli/src/main/java/org/apache/any23/cli/ExtractorDocumentation.java
- cli/src/main/java/org/apache/any23/cli/MicrodataParser.java
- cli/src/main/java/org/apache/any23/cli/MimeDetector.java
- cli/src/main/java/org/apache/any23/cli/PluginVerifier.java
- cli/src/main/java/org/apache/any23/cli/Rover.java
- cli/src/main/java/org/apache/any23/cli/ToolRunner.java
- cli/src/main/java/org/apache/any23/cli/VocabPrinter.java
- cli/src/test/java/org/apache/any23/cli/MicrodataParserTest.java
- cli/src/test/java/org/apache/any23/cli/MimeDetectorTest.java
- cli/src/test/java/org/apache/any23/cli/RoverTest.java
- cli/src/test/java/org/apache/any23/cli/SimpleRoverTest.java
- cli/src/test/java/org/apache/any23/cli/ToolTestBase.java
- cli/src/test/java/org/apache/any23/cli/YAMLRoverTest.java
- core/src/main/java/org/apache/any23/extractor/SingleDocumentExtraction.java
- core/src/main/java/org/apache/any23/extractor/rdf/BaseRDFExtractor.java
- core/src/test/java/org/apache/any23/extractor/html/AbstractExtractorTestCase.java
- core/src/test/java/org/apache/any23/extractor/rdfa/RDFa11ExtractorTest.java
- core/src/test/java/org/apache/any23/vocab/RDFSchemaUtilsTest.java
- plugins/office-scraper/src/test/java/org/apache/any23/plugin/officescraper/ExcelExtractorTest.java
- test-resources/src/test/resources/html/rdfa/attribute-already-specified.html
I disallowed duplicate attribute keys in html to avoid `org.xml.sax.SAXParseException`s.
Along the way, I also cleaned up some annoying or unnecessary logging/console output produced by our massive suite of test cases.
Also cleaned up some javadoc/miscellaneous items.
> ANY23-380 disallow duplicate attribute keys

- encoding/src/main/java/org/apache/any23/encoding/TikaEncodingDetector.java
- encoding/src/test/java/org/apache/any23/encoding/TikaEncodingDetectorTest.java
1. Increase default sniff limit for text charset detection from 12000 bytes to 65536 bytes
2. Include results of xml declaration encoding detection
3. Include results of html meta charset encoding detection
> ANY23-385 improve encoding detection

- core/src/main/java/org/apache/any23/writer/RDFWriterTripleHandler.java
Make the constructor of `RDFWriterTripleHandler` and its field `writer` protected, as [discussed](https://issues.apache.org/jira/browse/ANY23-388?focusedCommentId=16580679&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16580679) by me, @lewismc and @HansBrende. This replaces PR #116
> ANY23-388 Make field writer and constructor protected

- service/pom.xml
Add configuration to load src/main/resources.
Plugin settings are useful only for debugging purposes.
* loads content of `src/main/` into web application resources
> ANY23-392: Add configuration for maven-jetty-plugin

- core/src/test/java/org/apache/any23/extractor/microdata/MicrodataExtractorTest.java
I created a microdata unit test which tests against the latest online [microdata test suite](http://w3c.github.io/microdata-rdf/tests/).
Currently, 30 out of 84 total tests are failing!
*Note: the tests are relaxed such that the expected model is only required to be a subset of the actual model, and not necessarily the other way around. Requiring strict isomorphism, on the other hand, causes 83 out of 84 tests to fail.*
**The 30 failing tests are as follows:**
Test 0002: Item with no itemtype and 2 elements with equivalent itemprop
Test 0003: Item with itemprop having two properties
Test 0046: Use of time with `@datetime` xsd:time
Test 0047: Use of time with `@datetime` xsd:dateTime
Test 0048: Use of time with `@datetime` xsd:duration
Test 0049: Use of time with `@datetime` invalid
Test …
> ANY23-67 test against online microdata test-suite

- service/pom.xml
This issue addresses https://issues.apache.org/jira/browse/ANY23-419
> ANY23-419 Add J2EE dependencies such that service runs under JDK11

- NOTICE.txt
- encoding/pom.xml
- encoding/src/main/java/org/apache/any23/encoding/EncodingUtils.java
- encoding/src/main/java/org/apache/any23/encoding/TikaEncodingDetector.java
- encoding/src/test/java/org/apache/any23/encoding/TikaEncodingDetectorTest.java
Improves TikaEncodingDetector by:
1. Not second-guessing UTF-8 if there is *any* indication that a stream is UTF-8-encoded. We can't afford false positives from obscure, obsolete charsets such as IBM500 (See [TIKA-2771](https://issues.apache.org/jira/browse/TIKA-2771)).
2. Taking entire stream into account rather than a prefix (this shouldn't be a huge memory issue, as we are already holding the entire stream in memory to pass to each extractor, and extractors such as RDFa already parse the entire content into a DOM before generating the triples. If we want to make Any23 "streaming"-capable in the future to reduce memory requirements, we can look into that, but for now, since we're not, we may as well use that to our advantage to be more accurate in charset detection.)
3. Taking …
> ANY23-418 improve TikaEncodingDetector

- service/src/test/java/org/apache/any23/servlet/ServletTest.java
This issue addresses https://issues.apache.org/jira/browse/ANY23-427 and also stabilizes tests.
> ANY23-427 http://semanticweb.org/ down causes tests to fail

- core/src/main/java/org/apache/any23/extractor/rdf/BaseRDFExtractor.java
- core/src/main/java/org/apache/any23/extractor/rdfa/BaseRDFaExtractor.java
- core/src/main/java/org/apache/any23/extractor/rdfa/JsoupScanner.java
- core/src/main/java/org/apache/any23/extractor/rdfa/RDFa11Extractor.java
- core/src/main/java/org/apache/any23/extractor/rdfa/RDFaExtractor.java
- core/src/main/java/org/apache/any23/extractor/rdfa/SemarglSink.java
- core/src/test/java/org/apache/any23/extractor/rdfa/RDFa11ExtractorTest.java
I've implemented the performance (and stability) improvements I suggested in [ANY23-443](https://issues.apache.org/jira/browse/ANY23-443) by getting rid of all the RDFa middlemen: 
Any23 → Jsoup → ~InputStream~ → ~RDF4J~ → ~XMLReader~ → RdfaParser → ~RDF4J~ → Any23
All tests pass.
> ANY23-443 improve speed & stability of RDFa extractors

- src/site/apt/configuration.apt
This PR addresses https://issues.apache.org/jira/browse/ANY23-440
> ANY23-440 any23 configuration documentation has a wrong property name

- pom.xml
Fixes:
commons-compress-1.18.jar (pkg:maven/org.apache.commons/commons-compress@1.18, cpe:2.3:a:apache:commons-compress:1.18:*:*:*:*:*:*:*, cpe:2.3:a:apache:commons_compress:1.18:*:*:*:*:*:*:*) : CVE-2019-12402
poi-4.1.0.jar (pkg:maven/org.apache.poi/poi@4.1.0, cpe:2.3:a:apache:poi:4.1.0:*:*:*:*:*:*:*) : CVE-2019-12415
> Updating Compress and POI to fix CVE issues

- pom.xml
This issue addresses the long standing broken build by simply upgrading jsonld-java to 0.13.1
https://issues.apache.org/jira/browse/ANY23-453
> ANY23-453 Upgrade jsonld-java to 0.13.1

- cli/src/main/java/org/apache/any23/cli/Rover.java
This PR addresses https://issues.apache.org/jira/browse/ANY23-458
PR address the following improved info to STDOUT. Note the improved info specifically for `--extractors` and `--format` flags.
```
rover      Apache Any23 Command Line Tool.
Usage: rover [options] input IRIs {<url>|<file>}+
Options:
-d, --defaultns
Override the default namespace used to produce statements.
-e, --extractors
a comma-separated list of extractors, e.g. rdf-xml,rdf-turtle,
etc. A complete extractor list can be obtained by calling ./any23
extractor --list
Default: [csv, html-embedded-jsonld, html-head-icbm, html-head-links, html-head-meta, html-head-title, html-mf-adr, html-mf-geo, html-mf-hcalendar, html-mf-hcard, html-mf-hlisting, html-mf-hrecipe, html-mf-hresume, html-mf-hreview, html-mf-hreview-aggregate, …
```
> ANY23-458 Improve extractor and writer information in Rover

- core/src/main/java/org/apache/any23/extractor/html/EmbeddedJSONLDExtractor.java
- core/src/main/java/org/apache/any23/extractor/html/HCardName.java
- core/src/main/java/org/apache/any23/extractor/html/HTMLMetaExtractor.java
- core/src/main/java/org/apache/any23/extractor/rdf/RDFParserFactory.java
- core/src/main/java/org/apache/any23/extractor/rdfa/RDFa11Parser.java
- core/src/main/java/org/apache/any23/extractor/yaml/ElementsProcessor.java
- core/src/main/java/org/apache/any23/filter/ExtractionContextBlocker.java
- core/src/main/java/org/apache/any23/writer/BenchmarkTripleHandler.java
- core/src/test/java/org/apache/any23/validator/DefaultValidatorTest.java
- core/src/test/java/org/apache/any23/vocab/VocabularyTest.java
Declaring inner classes non-static causes performance issues due to GC at Java. They should be defined as static wherever it can.
You can see related conversation here: https://stackoverflow.com/questions/20380600/gc-performance-hit-for-inner-class-vs-static-nested-class
> [ANY23-464] Performance improvement for inner classes

- core/src/main/java/org/apache/any23/extractor/html/HTMLDocument.java
StringBuilder should be used instead of String concatenation at loops due to performance reasons.
> [ANY23-465] StringBuilder is Used Instead of String Concatenation at Loop

- cli/pom.xml
- cli/src/main/assembly/bin.xml
- pom.xml
The long classpath is a known issue in the maven plug-in appassembler-maven-plugin. The description of the issue is here:
https://www.mojohaus.org/appassembler/appassembler-maven-plugin/faq.html#
This pull request solved this issue by implementing the "Booter" mechanism, which is described here:
https://www.mojohaus.org/appassembler/appassembler-maven-plugin/usage-booter.html
The generated any23.bat does not contain the long "set CLASSPATH=..." any more. The generated script runs on CMD even if the base path is very long.
> [ANY23-371] Any23 cannot start in CMD in Windows 10

- cli/pom.xml
- core/pom.xml
- encoding/pom.xml
- mime/pom.xml
- mime/src/main/java/org/apache/any23/mime/TikaMIMETypeDetector.java
- mime/src/test/java/org/apache/any23/mime/purifier/WhiteSpacesPurifierTest.java
- pom.xml
This PR supersedes https://github.com/apache/any23/pull/183 and addresses https://issues.apache.org/jira/browse/ANY23-496
> ANY23-496 Bump tika.version from 1.27 to 2.1.0

- api/pom.xml
- cli/pom.xml
- core/pom.xml
- csvutils/pom.xml
- encoding/pom.xml
- mime/pom.xml
- pom.xml
This issue addresses [ANY23-538](https://issues.apache.org/jira/browse/ANY23-538).
Due to the recent widespread upgrades to Log4j2 everywhere, it also addresses [ANY23-539](https://issues.apache.org/jira/browse/ANY23-539) and [ANY23-536](https://issues.apache.org/jira/browse/ANY23-536).
The introduction of the *ossindex-maven-plugin* and the additional rules to the *maven-enforcer-plugin* are ultimately aimed at making the Any23 build more secure.
> ANY23-538 Replace existing logging with Slf4j over log4j2

- core/src/main/java/org/apache/any23/rdf/RDFUtils.java
- core/src/main/java/org/apache/any23/util/MathUtils.java
- core/src/test/java/org/apache/any23/util/MathUtilsTest.java
- pom.xml
This issue addresses https://issues.apache.org/jira/browse/ANY23-553
> ANY23-553 Document MathUtils#md5 to warn that the weak hash algorithm is not to be used in a sensitive context

- pom.xml
- src/site/site.xml
Recent Fluido skins you are using can have updated breadcrumb that eases documentation edit: there is an "edit" icon that goes directly to page source on GitHub to provide a PR
> add edit source button in generated site

- api/src/main/resources/default-configuration.properties
- cli/src/main/assembly/README.txt
- pom.xml
release 2.7 is not fully reproducible: https://github.com/jvm-repo-rebuild/reproducible-central#org.apache.any23:apache-any23
there are a few issues https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/org/apache/any23/apache-any23-2.7.diffoscope
some are because of old plugins versions, some because of build timestamp put in generated content
this PR fixes issues, you can test by running:
```
mvn clean install -Papache-release -DskipTests -Dgpg.skip && mvn clean package -Papache-release -DskipTests -Dgpg.skip artifact:compare
```
> make build reproducible
